#!/usr/bin/env bash
#=============================================================
# https://github.com/xd003/clone
# File Name: clone
# Author: xd003
# Description: Clone bash script to be used for common fclone/gclone operations
# System Supported: Arch , Ubuntu/Debian , Fedora & Termux ( amd64 & arm64 )
#=============================================================

cecho() {
  local code="\033["
  case "$1" in
  black | bk) color="${code}0;30m" ;;
  red | r) color="${code}1;31m" ;;
  green | g) color="${code}1;32m" ;;
  yellow | y) color="${code}1;33m" ;;
  blue | b) color="${code}1;34m" ;;
  purple | p) color="${code}1;35m" ;;
  cyan | c) color="${code}1;36m" ;;
  gray | gr) color="${code}0;37m" ;;
  *) local text="$1" ;;
  esac
  [ -z "$text" ] && local text="$color$2${code}0m"
  echo -e "$text"
}

while true; do
  cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Copy
┋    (Copy files from source to dest, skipping already copied)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Move
┋    (Move files from source to dest, skipping already moved)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) Sync
┋    (Make source and dest identical, modifying destination only)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) Dedupe
┋    (Find duplicate files and delete/rename them)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋5) Size
┋    (Return the total size and number of objects)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋6) Listing
┋    (List all the files and folders)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋7) NCDU
┋    (Explore directory with text based UI)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋8) Empty Trash
┋    (You need to have Manager Permission in TD)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋9) Delete Empty Folders
┋    (Delete all Empty Folders recursively)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋10) Check
┋    (Check if the files in the source and destination match)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋11) Delete
┋    (Delete a file or a folder along with its content)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋12) Quit
┋    (Exit the Script)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF

  echo
  read -e -p "Enter your input : " opt
  echo
  case $opt in
  1)
    cecho b "Copy option has been selected"
    read -e -p "Enter the source folder id or url : " src
    src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    read -e -p "Enter the destination folder id or url : " dst
    dst=$(echo $dst | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    : > $HOME/easyclone/log.txt
    rclone --config=$HOME/easyclone/rc.conf copy gd:{$src} gd:{$dst} --drive-server-side-across-configs --ignore-existing --drive-acknowledge-abuse --drive-keep-revision-forever --stats=1s --stats-one-line -vP --checkers=320 --transfers=320 --drive-pacer-min-sleep=1ms --drive-pacer-burst=5000 --check-first --drive-chunk-size 128M --log-file $HOME/easyclone/log.txt
    ;;
  2)
    cecho b "Move option has been selected"
    read -e -p "Enter the source folder id or url : " src
    src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    read -e -p "Enter the destination folder id or url : " dst
    dst=$(echo $dst | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    : > $HOME/easyclone/log.txt
    rclone --config=$HOME/easyclone/rc.conf move gd:{$src} gd:{$dst} --drive-server-side-across-configs --ignore-existing --drive-acknowledge-abuse --drive-keep-revision-forever --stats=1s --stats-one-line -vP --checkers=320 --transfers=320 --drive-pacer-min-sleep=1ms --drive-pacer-burst=5000 --check-first --drive-chunk-size 128M --log-file $HOME/easyclone/log.txt
    ;;
  3)
    cecho b "Sync option has been selected"
    read -e -p "Enter the source folder id or url : " src
    src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    read -e -p "Enter the destination folder id or url : " dst
    dst=$(echo $dst | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    : > $HOME/easyclone/log.txt
    rclone --config=$HOME/easyclone/rc.conf sync gd:{$src} gd:{$dst} --drive-server-side-across-configs --drive-acknowledge-abuse --drive-keep-revision-forever --stats=1s --stats-one-line -vP --checkers=320 --transfers=320 --drive-pacer-min-sleep=1ms --drive-pacer-burst=5000 --check-first --drive-chunk-size 128M --log-file $HOME/easyclone/log.txt
    ;;
  4)
    cecho b "Dedupe option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Interactive
┋    (Use Dedupe Interactively)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Skip
┋    (Removes identical files then skips anything left)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) First
┋    (Removes identical files then keeps the first one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) Newest
┋    (Removes identical files then keeps the newest one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋5) Oldest
┋    (removes identical files then keeps the oldest one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋6) Largest
┋    (removes identical files then keeps the largest one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋7) Smallest
┋    (removes identical files then keeps the smallest one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋8) Rename
┋    (removes identical files then renames the rest to be different)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋9) Return to Main Menu
┋    (Restart the script from Main Menu)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Enter the Dedupe Operation Mode (1-9) : " dm
    if [[ $dm -ne 9 ]]; then
      read -e -p "Enter the folder id or url : " src
      src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    fi
    case $dm in
    1)
      cecho b "Dedupe Interactive option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf dedupe --dedupe-mode interactive gd:{$src} --verbose=2
      ;;
    2)
      cecho b "Dedupe Skip option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf dedupe --dedupe-mode skip gd:{$src} --verbose=2
      ;;
    3)
      cecho b "Dedupe First option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf dedupe --dedupe-mode first gd:{$src} --verbose=2
      ;;
    4)
      cecho b "Dedupe Newest option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf dedupe --dedupe-mode newest gd:{$src} --verbose=2
      ;;
    5)
      cecho b "Dedupe Oldest option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf dedupe --dedupe-mode oldest gd:{$src} --verbose=2
      ;;
    6)
      cecho b "Dedupe Largest option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf dedupe --dedupe-mode largest gd:{$src} --verbose=2
      ;;
    7)
      cecho b "Dedupe Smallest option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf dedupe --dedupe-mode smallest gd:{$src} --verbose=2
      ;;
    8)
      cecho b "Dedupe Rename option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf dedupe --dedupe-mode rename gd:{$src} --verbose=2
      ;;
    9)
      continue
      ;;
    esac

    ;;
  5)
    cecho b "Size option has been selected"
    read -e -p "Enter the folder id or url : " src
    src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    : > $HOME/easyclone/log.txt
    rclone --config=$HOME/easyclone/rc.conf size gd:{$src} --fast-list
    ;;
  6)
    cecho b "Listing option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) ls
┋    (List the objects in the path with size and path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) lsd
┋    (List all directories/containers/buckets in the path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) lsf
┋    (List directories and objects in remote:path formatted for parsing)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) lsjson
┋    (List directories and objects in the path in JSON format)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋5) lsl
┋    (List the objects in path with modification time, size and path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋6) tree
┋    (List the contents of the remote in a tree like fashion)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋7) Return to Main Menu
┋    (Restart the script from Main Menu)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Choose the listing type : " lt
    if [[ $lt -ne 7 ]]; then
      read -e -p "Enter the folder id or url : " src
      src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    fi
    case $lt in
    1)
      cecho b "Listing / ls option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf ls gd:{$src}
      ;;
    2)
      cecho b "Listing / lsd option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf lsd gd:{$src}
      ;;
    3)
      cecho b "Listing / lsf option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf lsf gd:{$src}
      ;;
    4)
      cecho b "Listing / lsjson option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf lsjson gd:{$src}
      ;;
    5)
      cecho b "Listing / lsl option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf lsl gd:{$src}
      ;;
    6)
      cecho b "Listing / tree option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf tree gd:{$src}
      ;;
    7)
      continue
      ;;
    esac
    ;;
  7)
    cecho b "NCDU option has been selected"
    read -e -p "Enter the folder id or url : " src
    src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    : > $HOME/easyclone/log.txt
    rclone --config=$HOME/easyclone/rc.conf ncdu gd:{$src} --fast-list
    ;;
  8)
    cecho b "Empty Trash option has been selected"
    read -e -p "Enter the folder id or url : " src
    src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    : > $HOME/easyclone/log.txt
    rclone --config=$HOME/easyclone/rc.conf delete gd:{$src} --drive-trashed-only=true --drive-use-trash=false --fast-list --verbose=2
    ;;
  9)
    cecho b "Delete Empty folders option has been selected"
    read -e -p "Enter the folder id or url : " src
    src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    : > $HOME/easyclone/log.txt
    rclone --config=$HOME/easyclone/rc.conf rmdirs gd:{$src} --leave-root
    ;;
  10)
    cecho b "Check option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Compare only Size
┋    (MD5/SHA1 is not considered here. Use this for a quick check)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Compare Size + MD5 / SHA1 Hash
┋    (Compares sizes and hashes and logs report of unmatched files .Very slow process)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) Compare after Downloading data locally
┋    (Download data from both the directories and Compare them on the fly .Use only if remote doesn't support hashes)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) Return to Main Menu
┋    (Restart the script from Main Menu)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Choose the Comparison Mode : " opt
    if [[ $opt -ne 4 ]]; then
      read -e -p "Enter the source folder id or url : " src
      src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
      read -e -p "Enter the destination folder id or url : " dst
      dst=$(echo $dst | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    fi
    case $opt in
    1)
      cecho b "Check / Compare only size option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf check gd:{$src} gd:{$dst} -P --drive-server-side-across-configs --fast-list --size-only
      ;;
    2)
      cecho b "Check / Compare size + MD5 option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf check gd:{$src} gd:{$dst} -P --drive-server-side-across-configs --fast-list
      ;;
    3)
      cecho b "Check / Compare locally downloaded date option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf check gd:{$src} gd:{$dst} -P --drive-server-side-across-configs --fast-list --download
      ;;
    4)
      continue
      ;;
    esac
    ;;
  11)
    cecho b "Delete option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Delete
┋    (Delete the contents of path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Deletefile
┋    (Delete a single file from path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) Purge
┋    (Delete the path and its content)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) Return to Main Menu
┋    (Restart the script from Main Menu)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Enter your input : " opt
    if [[ $opt -ne 4 ]]; then
      read -e -p "Enter the source folder id or url : " src
      src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
    fi
    case $opt in
    1)
      cecho b "Delete / Default option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf delete gd:{$src} -vP --stats-one-line --stats=15s --fast-list
      ;;
    2)
      cecho b "Delete / Deletet option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf deletefile gd:{$src} -vP --stats-one-line --stats=15s --fast-list
      ;;
    3)
      cecho b "Delete / Purge option has been selected"
      : > $HOME/easyclone/log.txt
      rclone --config=$HOME/easyclone/rc.conf purge gd:{$src} -vP --stats-one-line --stats=15s --fast-list
      ;;
    4)
      continue
      ;;
    esac
    ;;
  12)
    exit
    ;;
  esac
  if [[ "$?" ]]; then
      break
  fi
done
