#!/usr/bin/env bash
#=============================================================
# https://github.com/xd003/clone
# File Name: clone
# Author: xd003
# Description: Clone bash script to be used for common fclone operations
# System Supported: Arch , Ubuntu/Debian , Fedora & Termux
#=============================================================

cecho() {
        local code="\033["
        case "$1" in
                black  | bk) color="${code}0;30m";;
                red    |  r) color="${code}1;31m";;
                green  |  g) color="${code}1;32m";;
                yellow |  y) color="${code}1;33m";;
                blue   |  b) color="${code}1;34m";;
                purple |  p) color="${code}1;35m";;
                cyan   |  c) color="${code}1;36m";;
                gray   | gr) color="${code}0;37m";;
                *) local text="$1"
        esac
        [ -z "$text" ] && local text="$color$2${code}0m"
        echo -e "$text"
}

flags="--drive-server-side-across-configs --ignore-existing --drive-acknowledge-abuse --drive-keep-revision-forever --stats=1s --stats-one-line -vP --checkers=320 --transfers=320 --drive-pacer-min-sleep=1ms --drive-pacer-burst=5000 --check-first --drive-chunk-size 128M --log-file $HOME/easyclone"

cat << EOF 
1. Copy
2. Move
3. Sync
4. Dedupe
5. Size
6. Directory Listing
EOF

read -e -p "Enter your input : " opt
case $opt in
  1 )
  read -e -p "Enter the source folder id or url : " src
  read -e -p "Enter the destination folder id or url : " dst
  fclone copy gd:{$src} gd:{$dst} $flags
  ;;
  2 )
  read -e -p "Enter the source folder id or url : " src
  read -e -p "Enter the destination folder id or url : " dst
  fclone move gd:{$src} gd:{$dst} $flags
  ;;
  3 )
  read -e -p "Enter the source folder id or url : " src
  read -e -p "Enter the destination folder id or url : " dst
  fclone sync gd:{$src} gd:{$dst} $flags
  ;; 
  4 )
  
  ;;
  5 )
  read -e -p "Enter the folder id or url : " src
  fclone size gd:{$src}
  6 )
  
  ;;
esac
