#!/usr/bin/env bash
#=============================================================
# https://github.com/xd003/clone
# File Name: clone
# Author: xd003
# Description: Clone bash script to be used for common fclone/gclone operations
# System Supported: Arch , Ubuntu/Debian , Fedora & Termux ( amd64 & arm64 )
#=============================================================

cecho() {
  local code="\033["
  case "$1" in
  black | bk) color="${code}0;30m" ;;
  red | r) color="${code}1;31m" ;;
  green | g) color="${code}1;32m" ;;
  yellow | y) color="${code}1;33m" ;;
  blue | b) color="${code}1;34m" ;;
  purple | p) color="${code}1;35m" ;;
  cyan | c) color="${code}1;36m" ;;
  gray | gr) color="${code}0;37m" ;;
  *) local text="$1" ;;
  esac
  [ -z "$text" ] && local text="$color$2${code}0m"
  echo -e "$text"
}
# Sasync Script

# Variable
conf="$HOME/easyclone/rc.conf"
ehome="$(echo $HOME)"
uflags="--fast-list --drive-server-side-across-configs --drive-acknowledge-abuse --drive-keep-revision-forever --stats=10s -vP --drive-use-trash=false --drive-stop-on-upload-limit --use-mmap --user-agent randomstringxyz --log-file $HOME/easyclone/log.txt"
jc="$(ls -l $HOME/easyclone/accounts | egrep -c '^-')"
rjc1="$(shuf -i 1-$jc -n 1)"
rjc2="$(shuf -i 1-$jc -n 1)"

# Functions
fsrc() {
  : > $HOME/easyclone/log.txt
  sed -i '/^team_drive/d' $conf
  sed -i '/^root_folder_id/d' $conf
  cecho b "[When you need to enter folder id/url , you can enter b to choose a folder id from your bookmark.txt]"
  read -e -p "Enter the source folder id or url : " src
  if [ "$src" == "b" ]; then
    cat $HOME/easyclone/bookmark.txt | nl -w1 -s'• '
    echo
    read -e -p "Enter the number corresponding to the folder_id which you want to use : " NUM
    src="$(cat $HOME/easyclone/bookmark.txt | awk 'NF>1{print $NF}' | sed "${NUM}q;d")"
  else
    src=$(echo $src | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
  fi
  case $src in
  0*)
    sed -i "4iteam_drive = $src" $conf
    ;;
  1*)
    sed -i "4iroot_folder_id = $src" $conf
    ;;
  esac
  sed -ri "5s/[[:digit:]]+.json/$rjc1.json/" $conf
}

fdst() {
  read -e -p "Enter the destination folder id or url : " dst
  if [ "$dst" == "b" ]; then
    cat $HOME/easyclone/bookmark.txt | nl -w1 -s'• '
    echo
    read -e -p "Enter the number corresponding to the folder_id which you want to use : " NUM
    dst="$(cat $HOME/easyclone/bookmark.txt | awk 'NF>1{print $NF}' | sed "${NUM}q;d")"
  else
    dst=$(echo $dst | sed -E 's~.*[/=]([01A-Z][-_[:alnum:]]+)([?/].*|$)~\1~')
  fi
  case $dst in
  0*)
    sed -i "11iteam_drive = $dst" $conf
    ;;
  1*)
    sed -i "11iroot_folder_id = $dst" $conf
    ;;
  esac
  sed -ri "12s/[[:digit:]]+.json/$rjc2.json/" $conf
}

sclone="$(which clone)"
check="$(cat "$sclone" | sed -n '26p' |grep 'Sasync')"
if [ -z "${check}" ] ; then
    cecho g "Cloning Tool : Lclone"
else
    cecho g "Cloning Tool : Rclone + Sasync"
fi
sleep 1
echo

while true; do
  cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Copy
┋    (Copy files from source to dest, skipping already copied)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Move
┋    (Move files from source to dest, skipping already moved)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) Sync
┋    (Make source and dest identical, modifying destination only)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) Dedupe
┋    (Find duplicate files and delete/rename them)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋5) Size
┋    (Return the total size and number of objects)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋6) Listing
┋    (List all the files and folders)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋7) NCDU
┋    (Explore directory with text based UI)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋8) Upload | Download
┋    (Move , Copy or Sync Local Folder to Drive OR Download files locally)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋9) Empty Trash
┋    (You need to have Manager Permission in TD)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋10) Delete Empty Folders
┋    (Delete all Empty Folders recursively)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋11) Check
┋    (Check if the files in the source and destination match)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋12) Delete
┋    (Delete a file or a folder along with its content)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋13) Switch Cloning Tool
┋    (Switch Between Sasync & Lclone on the go)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋14) Quit
┋    (Exit the Script)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF

  echo
  read -e -p "Enter your input : " opt
  echo
  case $opt in
  1)
    cecho y "Copy option has been selected"
    fsrc 
    fdst
    echo
    cecho b "Do you want to use --ignore-existing flag for this process ?"
    cecho b "[Only use it if your source/destination doesn't contain modification of any file overwritten with same name as even after having different size they will be considered equal and ignored]"
    read -e -p "Enter Your Input [y/n] : " ig
    case $ig in
    [Yy]*)
      (cd $HOME/easyclone/sasync; bash sasync set.copyig)
      ;;
    [Nn]*)
      (cd $HOME/easyclone/sasync; bash sasync set.copy)
      ;;
    esac
    ;;
  2)
    cecho y "Move option has been selected"
    fsrc
    fdst
    echo
    cecho b "Do you want to use --ignore-existing flag for this process ?"
    cecho b "[Only use it if your source/destination doesn't contain modification of any file overwritten with same name as even after having different size they will be considered equal and ignored]"
    read -e -p "Enter Your Input [y/n] : " ig
    case $ig in
    [Yy]*)
      (cd $HOME/easyclone/sasync; bash sasync set.moveig)
      ;;
    [Nn]*)
      (cd $HOME/easyclone/sasync; bash sasync set.move)
      ;;
    esac
    ;;
  3)
    cecho y "Sync option has been selected"
    fsrc
    fdst
    echo
    cecho b "Do you want to use --ignore-existing flag for this process ?"
    cecho b "[Only use it if your source/destination doesn't contain modification of any file overwritten with same name as even after having different size they will be considered equal and ignored]"
    read -e -p "Enter Your Input [y/n] : " ig
    case $ig in
    [Yy]*)
      (cd $HOME/easyclone/sasync; bash sasync set.syncig)
      ;;
    [Nn]*)
      (cd $HOME/easyclone/sasync; bash sasync set.sync)
      ;;
    esac
    ;;
  4)
    cecho y "Dedupe option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Interactive
┋    (Use Dedupe Interactively)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Skip
┋    (Removes identical files then skips anything left)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) First
┋    (Removes identical files then keeps the first one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) Newest
┋    (Removes identical files then keeps the newest one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋5) Oldest
┋    (removes identical files then keeps the oldest one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋6) Largest
┋    (removes identical files then keeps the largest one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋7) Smallest
┋    (removes identical files then keeps the smallest one)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋8) Rename
┋    (removes identical files then renames the rest to be different)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋9) Return to Main Menu
┋    (Restart the script from Main Menu)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Enter the Dedupe Operation Mode (1-9) : " dm
    if [[ $dm -ne 9 ]]; then
      fsrc
    fi
    case $dm in
    1)
      cecho b "Dedupe Interactive option has been selected"
      rclone --config=$conf dedupe --dedupe-mode interactive src: --fast-list --verbose=2
      ;;
    2)
      cecho b "Dedupe Skip option has been selected"
      rclone --config=$conf dedupe --dedupe-mode skip src: --fast-list --verbose=2
      ;;
    3)
      cecho b "Dedupe First option has been selected"
      rclone --config=$conf dedupe --dedupe-mode first src: --fast-list --verbose=2
      ;;
    4)
      cecho b "Dedupe Newest option has been selected"
      rclone --config=$conf dedupe --dedupe-mode newest src: --fast-list --verbose=2
      ;;
    5)
      cecho b "Dedupe Oldest option has been selected"
      rclone --config=$conf dedupe --dedupe-mode oldest src: --fast-list --verbose=2
      ;;
    6)
      cecho b "Dedupe Largest option has been selected"
      rclone --config=$conf dedupe --dedupe-mode largest src: --fast-list --verbose=2
      ;;
    7)
      cecho b "Dedupe Smallest option has been selected"
      rclone --config=$conf dedupe --dedupe-mode smallest src: --fast-list --verbose=2
      ;;
    8)
      cecho b "Dedupe Rename option has been selected"
      rclone --config=$conf dedupe --dedupe-mode rename src: --fast-list --verbose=2
      ;;
    9)
      continue
      ;;
    esac

    ;;
  5)
    cecho y "Size option has been selected"
    fsrc
    rclone --config=$conf size src: --fast-list
    ;;
  6)
    cecho y "Listing option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) ls
┋    (List the objects in the path with size and path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) lsd
┋    (List all directories/containers/buckets in the path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) lsf
┋    (List directories and objects in remote:path formatted for parsing)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) lsjson
┋    (List directories and objects in the path in JSON format)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋5) lsl
┋    (List the objects in path with modification time, size and path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋6) tree
┋    (List the contents of the remote in a tree like fashion)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋7) Return to Main Menu
┋    (Restart the script from Main Menu)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Choose the listing type : " lt
    if [[ $lt -ne 7 ]]; then
      fsrc
    fi
    case $lt in
    1)
      cecho b "Listing / ls option has been selected"
      rclone --config=$conf ls src:
      ;;
    2)
      cecho b "Listing / lsd option has been selected"
      rclone --config=$conf lsd src:
      ;;
    3)
      cecho b "Listing / lsf option has been selected"
      rclone --config=$conf lsf src:
      ;;
    4)
      cecho b "Listing / lsjson option has been selected"
      rclone --config=$conf lsjson src:
      ;;
    5)
      cecho b "Listing / lsl option has been selected"
      rclone --config=$conf lsl src:
      ;;
    6)
      cecho b "Listing / tree option has been selected"
      rclone --config=$conf tree src:
      ;;
    7)
      continue
      ;;
    esac
    ;;
  7)
    cecho y "NCDU option has been selected"
    fsrc
    rclone --config=$conf ncdu src: --fast-list 2>/dev/null
    ;;
  8)
    cecho y "Upload | Download option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Upload + Copy
┋    (Copy file/folder locally to drive, skipping already copied)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Upload + Move
┋    (Move file/folder locally to drive, skipping already moved)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) Upload + Sync
┋    (Make local and drive file/folder identical, modifying drive only)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) Download
┋    (Download content locally from Google Drive)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋5) Return to Main Menu
┋    (Restart the script from Main Menu)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Choose the appropriate option : " upl
    if [[ $upl -ne 4 ]] && [[ $upl -ne 5 ]] ; then
      read -e -p "Enter the path of the folder which you want to upload : " src
      src="$(eval echo "$src")"
      : > $HOME/easyclone/log.txt && sed -i '/^team_drive/d' $conf && sed -i '/^root_folder_id/d' $conf && fdst
    fi

    if [ "$upl" == "4" ] ; then
      fsrc
      read -e -p "Enter the path where you want to download files locally : " dst
      dst="$(eval echo "$dst")"
    fi
    case $upl in
    1)
      lclone --config=$conf copy "$src" dst: $uflags
    ;;
    2)
      lclone --config=$conf move "$src" dst: $uflags --delete-empty-src-dirs
    ;;
    3)
      lclone --config=$conf sync "$src" dst: $uflags
    ;;
    4)
      lclone --config=$conf copy src: "$dst" $uflags
    ;;
    5)
      continue
    ;;
    esac
  ;;
  9)
    cecho y "Empty Trash option has been selected"
    fsrc
    rclone --config=$conf delete src: --drive-trashed-only=true --drive-use-trash=false --fast-list --verbose=2 --log-file $HOME/easyclone/log.txt
    ;;
  10)
    cecho y "Delete Empty folders option has been selected"
    fsrc
    rclone --config=$conf rmdirs src: --leave-root --fast-list --log-file $HOME/easyclone/log.txt
    ;;
  11)
    cecho y "Check option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Compare only Size
┋    (MD5/SHA1 is not considered here. Use this for a quick check)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Compare Size + MD5 / SHA1 Hash
┋    (Compares sizes and hashes and logs report of unmatched files. Very slow process)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) Compare after Downloading data locally
┋    (Download data from both the directories and Compare them on the fly. Use only if remote doesn't support hashes)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) Return to Main Menu
┋    (Restart the script from Main Menu)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Choose the Comparison Mode : " opt
    if [[ $opt -ne 4 ]]; then
      fsrc
      fdst
    fi
    case $opt in
    1)
      cecho b "Check / Compare only size option has been selected"
      rclone --config=$conf check src: dst: -P --drive-server-side-across-configs --fast-list --size-only
      ;;
    2)
      cecho b "Check / Compare size + MD5 option has been selected"
      rclone --config=$conf check src: dst: -P --drive-server-side-across-configs --fast-list
      ;;
    3)
      cecho b "Check / Compare locally downloaded date option has been selected"
      rclone --config=$conf check src: dst: -P --drive-server-side-across-configs --fast-list --download
      ;;
    4)
      continue
      ;;
    esac
    ;;
  12)
    cecho y "Delete option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Delete
┋    (Delete the contents of path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Deletefile
┋    (Delete a single file from path)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) Purge
┋    (Delete the path and its content)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋4) Return to Main Menu
┋    (Restart the script from Main Menu)
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Enter your input : " opt
    if [[ $opt -ne 4 ]]; then
      fsrc
    fi
    case $opt in
    1)
      cecho b "Delete / Default option has been selected"
      rclone --config=$conf delete src: -vP --stats-one-line --stats=15s --fast-list --log-file $HOME/easyclone/log.txt
      ;;
    2)
      cecho b "Delete / Deletet option has been selected"
      rclone --config=$conf deletefile src: -vP --stats-one-line --stats=15s --fast-list --log-file $HOME/easyclone/log.txt
      ;;
    3)
      cecho b "Delete / Purge option has been selected"
      rclone --config=$conf purge src: -vP --stats-one-line --stats=15s --fast-list --log-file $HOME/easyclone/log.txt
      ;;
    4)
      continue
      ;;
    esac
    ;;
  13)
    cecho y "Switch Cloning Tool option has been selected"
    cat << EOF
┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋1) Sasync + Rclone
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋2) Lclone
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
┋3) Return to Main Menu
┋┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
EOF
    echo
    read -e -p "Enter your input : " opt
    if [[ $opt -ne 3 ]]; then
      if [ "$ehome" == "/data/data/com.termux/files/home" ]; then
        rm -rf $(which clone)
      else
        sudo rm -rf $(which clone)
      fi
      spath="$(which git)"
      spath=$(echo $spath | sed 's/\/git$//')
    fi
    case $opt in
    1)
      if [ "$ehome" == "/data/data/com.termux/files/home" ]; then
        ln -sf "$HOME/easyclone/rclone" "$spath/clone"
        chmod u+x $spath/clone
      else  
        sudo ln -sf "$HOME/easyclone/rclone" "$spath/clone"
        sudo chmod u+x $spath/clone
      fi
      cecho g "Cloning Tool switched to Sasync , Run clone again for change to take effect"
      ;;
    2)
      if [ "$ehome" == "/data/data/com.termux/files/home" ]; then
        ln -sf "$HOME/easyclone/lclone" "$spath/clone"
        chmod u+x $spath/clone
      else  
        sudo ln -sf "$HOME/easyclone/lclone" "$spath/clone"
        sudo chmod u+x $spath/clone
      fi
      cecho g "Cloning Tool switched to Lclone , Run clone again for change to take effect"
      ;;
    3)
      continue
      ;;
    esac
    ;;
  14)
    exit
    ;;
  esac
  if [[ "$?" ]]; then
      break
  fi
done
